[versions]
bouncycastle = "1.83"
detekt = "1.23.4"
kotlin = "2.3.10"
ktlint = "11.0.0"
spring = "1.1.6"
spring-boot = "4.0.0"
springdoc = "3.0.1"

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
spring = { id = "io.spring.dependency-management", version.ref = "spring" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }

[libraries]
bouncycastle-bcpkix = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bouncycastle" }
bouncycastle-bcprov = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncycastle" }
jackson-jaxb = { module = "com.fasterxml.jackson.module:jackson-module-jaxb-annotations" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
postgres = { module = "org.postgresql:postgresql" }
spring-configuration = { module = "org.springframework.boot:spring-boot-configuration-processor" }
spring-data = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-devtools = { module = "org.springframework.boot:spring-boot-devtools" }
spring-graphql = { module = "org.springframework.boot:spring-boot-starter-graphql" }
spring-graphql-test = { module = "org.springframework.graphql:spring-graphql-test" }
spring-oauth2 = { module = "org.springframework.boot:spring-boot-starter-oauth2-resource-server" }
spring-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-webflux = { module = "org.springframework:spring-webflux" }
springdoc-starter = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }